services:
  - type: web
    name: fastapi-mail-sender
    env: docker
    repo: https://github.com/sofiene-Ben/fastapi_email_sender
    region: oregon  # ou frankfurt si tu veux l’Europe
    plan: free
    envVars:
      - key: SMTP_SERVER
        value: smtp.example.com
      - key: SMTP_USER
        value: user@example.com
      - key: SMTP_PASSWORD
        value: password
      - KEY: MAX_FILE_SIZE
        value: 22000000
      - KEY: DEFAULT_RECIPIENT
        value: exemple@hotmail.com
      - key: CORS
        value: cors
      - KEY: API_KEY
        value: your_secret_key
      - KEY: DEBUG
        value: false
      - KEY: MAILGUN_API_KEY
        value: your_mailgun_api_key
      - key: MAILGUN_DOMAIN
        value: your_mailgun_domain
      - key: MAILGUN_FROM
        value: your_mailgun_from
      - key: MAILGUN_TO
        value: your_mailgun_to